version: '3.8'

services:
  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/litellm_config.yaml
      - ./.env:/app/.env
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - LITELLM_CONFIG_PATH=/app/litellm_config.yaml
    command: --config /app/litellm_config.yaml --port 4000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5 