repos:
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
    -   id: isort
        args: ["--profile", "black"] 
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        exclude: ^examples/
        args: []
        additional_dependencies:
            - pydantic>=2.0.0
            - types-PyYAML
            - openai>=1.63.0
            - typing-extensions>=4.0.0
            - pytest>=7.0.0
            - pytest-asyncio>=0.23.0
            # Add other type stubs as needed for your project's dependencies 
-   repo: local
    hooks:
    -   id: build-docs
        name: Build Documentation
        entry: bash -c 'pip install -e . "sphinx>=6.2.1" "sphinx-rtd-theme>=1.2.2" "sphinx-autodoc-typehints<2.0.0" "openai>=1.63.0" && python scripts/build_docs.py'
        language: python
        pass_filenames: false
        files: ^(src/|docs/source/) 